/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JFrames;

import static Classes.Bookings.calculateCharges;
import static Classes.Bookings.getDatesBetween;
import Classes.RoomAvailability;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JToggleButton;
import java.awt.BorderLayout;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import java.util.Stack;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author user
 */
public class BookARoom extends javax.swing.JInternalFrame {

    //create variables
    private static JToggleButton[] rooms;
    private Stack<JInternalFrame> frameStack = new Stack<>();

    /**
     * Creates new form BookARoom
     */
    public BookARoom() {
        initComponents();
        initializing();
    }

    public void initializing() {
        //remove borders
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 00));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        //creating array of rooms for methods use
        rooms = new JToggleButton[]{
            room101, room102, room103, room104, room105,
            room106, room107, room108, room109, room110,
            room201, room202, room203, room204, room205,
            room206, room207, room208, room209, room210
        };

        //setting all rooms to disable
        for (JToggleButton i : rooms) {
            i.setEnabled(false);
        }

        DefaultListModel<String> listModel = new DefaultListModel<>();
        listModel.clear();
        roomSelected.setModel(listModel);

        checkSelectedRoom(rooms);

        //limit check in dates to today and onwards
        checkInInput.setMinSelectableDate(new Date());
    }

    public void checkSelectedRoom(JToggleButton[] myRooms) {
        ActionListener toggleListener = (ActionEvent e) -> {
            JToggleButton[] rooms = myRooms;
            ArrayList<String> selectedRooms = new ArrayList<String>();
            for (JToggleButton i : rooms) {
                if (i.isSelected()) {
                    selectedRooms.add(i.getText());
                }
            }
            
            DefaultListModel<String> tempList = new DefaultListModel<>();
            for (String i : selectedRooms) {
                tempList.addElement(i);
            }
            roomSelected.setModel(tempList);
            updateCOnfirmBookingBtn();
        };
        for (JToggleButton i : myRooms) {
            i.addActionListener(toggleListener);
        }
    }

    public void updateCOnfirmBookingBtn() {
        DefaultListModel checkList = (DefaultListModel) roomSelected.getModel();
        boolean isEmpty = checkList.isEmpty();
        btnConfirmSelection.setEnabled(!isEmpty);
        ConfirmBtnWarning.setVisible(isEmpty);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkOutInput = new com.toedter.calendar.JDateChooser();
        checkInInput = new com.toedter.calendar.JDateChooser();
        checkRooms = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanelFloor1 = new javax.swing.JPanel();
        room102 = new javax.swing.JToggleButton();
        room106 = new javax.swing.JToggleButton();
        room104 = new javax.swing.JToggleButton();
        room108 = new javax.swing.JToggleButton();
        room110 = new javax.swing.JToggleButton();
        room105 = new javax.swing.JToggleButton();
        room109 = new javax.swing.JToggleButton();
        room107 = new javax.swing.JToggleButton();
        room103 = new javax.swing.JToggleButton();
        room101 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        room202 = new javax.swing.JToggleButton();
        room208 = new javax.swing.JToggleButton();
        room209 = new javax.swing.JToggleButton();
        room206 = new javax.swing.JToggleButton();
        room210 = new javax.swing.JToggleButton();
        room207 = new javax.swing.JToggleButton();
        room205 = new javax.swing.JToggleButton();
        room203 = new javax.swing.JToggleButton();
        room204 = new javax.swing.JToggleButton();
        room201 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        roomSelected = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        btnConfirmSelection = new javax.swing.JButton();
        ConfirmBtnWarning = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkOutInput1 = new com.toedter.calendar.JDateChooser();
        checkInInput1 = new com.toedter.calendar.JDateChooser();
        checkRooms1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanelFloor2 = new javax.swing.JPanel();
        room111 = new javax.swing.JToggleButton();
        room112 = new javax.swing.JToggleButton();
        room113 = new javax.swing.JToggleButton();
        room114 = new javax.swing.JToggleButton();
        room115 = new javax.swing.JToggleButton();
        room116 = new javax.swing.JToggleButton();
        room117 = new javax.swing.JToggleButton();
        room118 = new javax.swing.JToggleButton();
        room119 = new javax.swing.JToggleButton();
        room120 = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        room211 = new javax.swing.JToggleButton();
        room212 = new javax.swing.JToggleButton();
        room213 = new javax.swing.JToggleButton();
        room214 = new javax.swing.JToggleButton();
        room215 = new javax.swing.JToggleButton();
        room216 = new javax.swing.JToggleButton();
        room217 = new javax.swing.JToggleButton();
        room218 = new javax.swing.JToggleButton();
        room219 = new javax.swing.JToggleButton();
        room220 = new javax.swing.JToggleButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        roomSelected1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        btnConfirmSelection1 = new javax.swing.JButton();
        ConfirmBtnWarning1 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setMaximumSize(new java.awt.Dimension(757, 478));
        setMinimumSize(new java.awt.Dimension(757, 478));
        setPreferredSize(new java.awt.Dimension(757, 478));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setText("Check in Date");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("Check Out Date:");

        checkOutInput.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        checkInInput.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        checkInInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkInInputMouseClicked(evt);
            }
        });
        checkInInput.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                checkInInputPropertyChange(evt);
            }
        });

        checkRooms.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        checkRooms.setText("Check");
        checkRooms.setMaximumSize(new java.awt.Dimension(757, 478));
        checkRooms.setMinimumSize(new java.awt.Dimension(757, 478));
        checkRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRoomsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(checkOutInput, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(checkInInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(checkRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkInInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkOutInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(checkRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        jPanel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jPanelFloor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        room102.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room102.setText("102");

        room106.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room106.setText("106");

        room104.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room104.setText("104");

        room108.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room108.setText("108");
        room108.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room108ActionPerformed(evt);
            }
        });

        room110.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room110.setText("110");
        room110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room110ActionPerformed(evt);
            }
        });

        room105.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room105.setText("105");

        room109.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room109.setText("109");

        room107.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room107.setText("107");

        room103.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room103.setText("103");

        room101.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room101.setText("101");
        room101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room101ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFloor1Layout = new javax.swing.GroupLayout(jPanelFloor1);
        jPanelFloor1.setLayout(jPanelFloor1Layout);
        jPanelFloor1Layout.setHorizontalGroup(
            jPanelFloor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFloor1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFloor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFloor1Layout.createSequentialGroup()
                        .addComponent(room106)
                        .addGap(18, 18, 18)
                        .addComponent(room107)
                        .addGap(18, 18, 18)
                        .addComponent(room108)
                        .addGap(18, 18, 18)
                        .addComponent(room109)
                        .addGap(18, 18, 18)
                        .addComponent(room110))
                    .addGroup(jPanelFloor1Layout.createSequentialGroup()
                        .addComponent(room101)
                        .addGap(18, 18, 18)
                        .addComponent(room102)
                        .addGap(18, 18, 18)
                        .addComponent(room103)
                        .addGap(18, 18, 18)
                        .addComponent(room104)
                        .addGap(18, 18, 18)
                        .addComponent(room105)))
                .addContainerGap())
        );
        jPanelFloor1Layout.setVerticalGroup(
            jPanelFloor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFloor1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFloor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room101, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room102, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room103, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room104, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room105, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanelFloor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room106, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room107, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room108, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room109, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room110, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanelFloor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelFloor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Floor 1", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        room202.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room202.setText("202");

        room208.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room208.setText("208");
        room208.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room208ActionPerformed(evt);
            }
        });

        room209.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room209.setText("209");

        room206.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room206.setText("206");

        room210.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room210.setText("210");

        room207.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room207.setText("207");

        room205.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room205.setText("205");

        room203.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room203.setText("203");

        room204.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room204.setText("204");

        room201.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        room201.setText("201");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(room206)
                        .addGap(18, 18, 18)
                        .addComponent(room207)
                        .addGap(18, 18, 18)
                        .addComponent(room208)
                        .addGap(18, 18, 18)
                        .addComponent(room209)
                        .addGap(18, 18, 18)
                        .addComponent(room210))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(room201)
                        .addGap(18, 18, 18)
                        .addComponent(room202)
                        .addGap(18, 18, 18)
                        .addComponent(room203)
                        .addGap(18, 18, 18)
                        .addComponent(room204)
                        .addGap(18, 18, 18)
                        .addComponent(room205)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room201, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room202, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room203, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room204, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room205, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room207, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room208, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room209, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room210, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room206, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Floor 2", jPanel3);

        jPanel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        roomSelected.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        roomSelected.setEnabled(false);
        roomSelected.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                roomSelectedValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(roomSelected);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("Rooms Selected:");

        btnConfirmSelection.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnConfirmSelection.setText("Confirm Selection");
        btnConfirmSelection.setEnabled(false);
        btnConfirmSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSelectionActionPerformed(evt);
            }
        });

        ConfirmBtnWarning.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        ConfirmBtnWarning.setForeground(new java.awt.Color(255, 51, 0));
        ConfirmBtnWarning.setText("Please choose a room first!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmSelection)
                            .addComponent(ConfirmBtnWarning)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnConfirmSelection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConfirmBtnWarning)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jInternalFrame1.setMaximumSize(new java.awt.Dimension(757, 478));
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(757, 478));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(757, 478));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Check in Date");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Check Out Date:");

        checkRooms1.setText("Check");
        checkRooms1.setMaximumSize(new java.awt.Dimension(757, 478));
        checkRooms1.setMinimumSize(new java.awt.Dimension(757, 478));
        checkRooms1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRooms1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(checkOutInput1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(checkInInput1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(checkRooms1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkInInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkOutInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(checkRooms1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane2.setAutoscrolls(true);
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanelFloor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        room111.setText("102");

        room112.setText("106");

        room113.setText("104");

        room114.setText("108");
        room114.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room114ActionPerformed(evt);
            }
        });

        room115.setText("110");
        room115.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room115ActionPerformed(evt);
            }
        });

        room116.setText("105");

        room117.setText("109");

        room118.setText("107");

        room119.setText("103");

        room120.setText("101");
        room120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room120ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFloor2Layout = new javax.swing.GroupLayout(jPanelFloor2);
        jPanelFloor2.setLayout(jPanelFloor2Layout);
        jPanelFloor2Layout.setHorizontalGroup(
            jPanelFloor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFloor2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFloor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFloor2Layout.createSequentialGroup()
                        .addComponent(room112)
                        .addGap(18, 18, 18)
                        .addComponent(room118)
                        .addGap(18, 18, 18)
                        .addComponent(room114)
                        .addGap(18, 18, 18)
                        .addComponent(room117)
                        .addGap(18, 18, 18)
                        .addComponent(room115))
                    .addGroup(jPanelFloor2Layout.createSequentialGroup()
                        .addComponent(room120)
                        .addGap(18, 18, 18)
                        .addComponent(room111)
                        .addGap(18, 18, 18)
                        .addComponent(room119)
                        .addGap(18, 18, 18)
                        .addComponent(room113)
                        .addGap(18, 18, 18)
                        .addComponent(room116)))
                .addContainerGap())
        );
        jPanelFloor2Layout.setVerticalGroup(
            jPanelFloor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFloor2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFloor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room120, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room111, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room119, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room113, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room116, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanelFloor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room112, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room118, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room114, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room117, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room115, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanelFloor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelFloor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Floor 1", jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        room211.setText("202");

        room212.setText("208");
        room212.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room212ActionPerformed(evt);
            }
        });

        room213.setText("209");

        room214.setText("206");

        room215.setText("210");

        room216.setText("207");

        room217.setText("205");

        room218.setText("203");

        room219.setText("204");

        room220.setText("201");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(room214)
                        .addGap(18, 18, 18)
                        .addComponent(room216)
                        .addGap(18, 18, 18)
                        .addComponent(room212)
                        .addGap(18, 18, 18)
                        .addComponent(room213)
                        .addGap(18, 18, 18)
                        .addComponent(room215))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(room220)
                        .addGap(18, 18, 18)
                        .addComponent(room211)
                        .addGap(18, 18, 18)
                        .addComponent(room218)
                        .addGap(18, 18, 18)
                        .addComponent(room219)
                        .addGap(18, 18, 18)
                        .addComponent(room217)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room220, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room211, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room218, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room219, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room217, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room216, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room212, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room213, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room215, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room214, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Floor 2", jPanel8);

        jPanel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        roomSelected1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        roomSelected1.setEnabled(false);
        roomSelected1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                roomSelected1ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(roomSelected1);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Rooms Selected:");

        btnConfirmSelection1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfirmSelection1.setText("Confirm Selection");
        btnConfirmSelection1.setEnabled(false);
        btnConfirmSelection1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSelection1ActionPerformed(evt);
            }
        });

        ConfirmBtnWarning1.setForeground(new java.awt.Color(255, 51, 0));
        ConfirmBtnWarning1.setText("Please choose a room first!");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmSelection1)
                            .addComponent(ConfirmBtnWarning1)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnConfirmSelection1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConfirmBtnWarning1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane2)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 372, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 373, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRoomsActionPerformed
        // TODO add your handling code here:
        //unselect all room toggle buttons
        for (JToggleButton i : rooms) {
            i.setSelected(false);
        }

        //clear roomSelected jList
        DefaultListModel roomsToClearModel = (DefaultListModel) roomSelected.getModel();
        roomsToClearModel.clear();
        
        //Receive input for check in and check out dates
        Date dateIn = checkInInput.getDate();
        Date dateOut = checkOutInput.getDate();
        ArrayList<String> datesNeeded = getDatesBetween(dateIn, dateOut);
        for (JToggleButton room : rooms) {
            room.setEnabled(true);
        }
        ArrayList<String> notAvailable = RoomAvailability.checkAvailability(datesNeeded, null);
        for (JToggleButton room : rooms) {
            if (notAvailable.contains(room.getText())) {
                room.setEnabled(false);
            }
        }

    }//GEN-LAST:event_checkRoomsActionPerformed

    private void room208ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room208ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room208ActionPerformed

    private void btnConfirmSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSelectionActionPerformed
        // TODO add your handling code here:
        ConfirmBooking targetFrame = new ConfirmBooking(frameStack);

        //setting all data on the new frame
        targetFrame.setRoomSelected(roomSelected.getModel());
        // get the dates in string format
        Calendar calIn = Calendar.getInstance();
        calIn.setTime(checkInInput.getDate());
        Calendar calOut = Calendar.getInstance();
        calOut.setTime(checkOutInput.getDate());
        int tempInYear = calIn.get(Calendar.YEAR);
        int tempInMonth = 1 + (calIn.get(Calendar.MONTH));
        int tempInDay = calIn.get(Calendar.DAY_OF_MONTH);
        String strDateIn = (String.valueOf(tempInYear)) + (String.valueOf(tempInMonth < 10 ? "0" + tempInMonth : tempInMonth)) + (String.valueOf(tempInDay < 10 ? "0" + tempInDay : tempInDay));
        int tempOutYear = calOut.get(Calendar.YEAR);
        int tempOutMonth = 1 + (calOut.get(Calendar.MONTH));
        int tempOutDay = calOut.get(Calendar.DAY_OF_MONTH);
        String strDateOut = (String.valueOf(tempOutYear)) + (String.valueOf(tempOutMonth < 10 ? "0" + tempOutMonth : tempOutMonth)) + (String.valueOf(tempOutDay < 10 ? "0" + tempOutDay : tempOutDay));

        //set the dates into their corresponding JTextField
        targetFrame.getChoosenDateIn().setText(strDateIn);
        targetFrame.getChoosenDateOut().setText(strDateOut);

        //get the charges        
        Date dateIn = checkInInput.getDate();
        Date dateOut = checkOutInput.getDate();
        String[] charges = calculateCharges(dateIn, dateOut, roomSelected.getModel().getSize());
        //ArrayLIst<String> charges = 
        //[0-nights, 1-roomCharges, 2-tourismTax, 3-serviceTax, 4-totalCharges]

        targetFrame.getNightsStayed().setText(charges[0]);
        targetFrame.getRoomCharges().setText(charges[1]);
        targetFrame.gettTax().setText(charges[2]);
        targetFrame.getsTax().setText(charges[3]);
        targetFrame.getTotalCharges().setText(charges[4]);

        //remove current JInternalFrame and show next JInternalFrame
        JDesktopPane ws = getDesktopPane();
        //push current BookARoom InternalFrame into the frame stack
        JInternalFrame currentFrame = ws.getSelectedFrame();
        frameStack.push(currentFrame);

        ws.setLayout(new BorderLayout());
        ws.removeAll();
        ws.add(targetFrame, BorderLayout.CENTER);
        targetFrame.setVisible(true);
    }//GEN-LAST:event_btnConfirmSelectionActionPerformed

    private void room108ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room108ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room108ActionPerformed

    private void room110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room110ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room110ActionPerformed

    private void room101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room101ActionPerformed

    private void roomSelectedValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_roomSelectedValueChanged
    }//GEN-LAST:event_roomSelectedValueChanged

    private void checkRooms1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRooms1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkRooms1ActionPerformed

    private void room114ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room114ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room114ActionPerformed

    private void room115ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room115ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room115ActionPerformed

    private void room120ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room120ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room120ActionPerformed

    private void room212ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room212ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room212ActionPerformed

    private void roomSelected1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_roomSelected1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_roomSelected1ValueChanged

    private void btnConfirmSelection1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSelection1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmSelection1ActionPerformed

    private void checkInInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInInputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInInputMouseClicked

    private void checkInInputPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_checkInInputPropertyChange
        // TODO add your handling code here:
        Date selected = checkInInput.getDate();
        if (selected != null) {
            // limit check out date dates after check In Date
            Calendar targetMinDate = Calendar.getInstance();
            targetMinDate.setTime(selected);
            targetMinDate.add(Calendar.DAY_OF_MONTH, 1);
            Date checkInOnwards = targetMinDate.getTime();
            checkOutInput.setMinSelectableDate(checkInOnwards);
            checkOutInput.setDate(null);
        }
    }//GEN-LAST:event_checkInInputPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmBtnWarning;
    private javax.swing.JLabel ConfirmBtnWarning1;
    private javax.swing.JButton btnConfirmSelection;
    private javax.swing.JButton btnConfirmSelection1;
    private com.toedter.calendar.JDateChooser checkInInput;
    private com.toedter.calendar.JDateChooser checkInInput1;
    private com.toedter.calendar.JDateChooser checkOutInput;
    private com.toedter.calendar.JDateChooser checkOutInput1;
    private javax.swing.JButton checkRooms;
    private javax.swing.JButton checkRooms1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelFloor1;
    private javax.swing.JPanel jPanelFloor2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton room101;
    private javax.swing.JToggleButton room102;
    private javax.swing.JToggleButton room103;
    private javax.swing.JToggleButton room104;
    private javax.swing.JToggleButton room105;
    private javax.swing.JToggleButton room106;
    private javax.swing.JToggleButton room107;
    private javax.swing.JToggleButton room108;
    private javax.swing.JToggleButton room109;
    private javax.swing.JToggleButton room110;
    private javax.swing.JToggleButton room111;
    private javax.swing.JToggleButton room112;
    private javax.swing.JToggleButton room113;
    private javax.swing.JToggleButton room114;
    private javax.swing.JToggleButton room115;
    private javax.swing.JToggleButton room116;
    private javax.swing.JToggleButton room117;
    private javax.swing.JToggleButton room118;
    private javax.swing.JToggleButton room119;
    private javax.swing.JToggleButton room120;
    private javax.swing.JToggleButton room201;
    private javax.swing.JToggleButton room202;
    private javax.swing.JToggleButton room203;
    private javax.swing.JToggleButton room204;
    private javax.swing.JToggleButton room205;
    private javax.swing.JToggleButton room206;
    private javax.swing.JToggleButton room207;
    private javax.swing.JToggleButton room208;
    private javax.swing.JToggleButton room209;
    private javax.swing.JToggleButton room210;
    private javax.swing.JToggleButton room211;
    private javax.swing.JToggleButton room212;
    private javax.swing.JToggleButton room213;
    private javax.swing.JToggleButton room214;
    private javax.swing.JToggleButton room215;
    private javax.swing.JToggleButton room216;
    private javax.swing.JToggleButton room217;
    private javax.swing.JToggleButton room218;
    private javax.swing.JToggleButton room219;
    private javax.swing.JToggleButton room220;
    private javax.swing.JList<String> roomSelected;
    private javax.swing.JList<String> roomSelected1;
    // End of variables declaration//GEN-END:variables
}
