/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class LandingPage extends javax.swing.JFrame {

    private boolean pauseTabChange = false;

    /**
     * Creates new form Parent
     */
    public LandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPaneContainer = new javax.swing.JTabbedPane();
        Workspace = new javax.swing.JDesktopPane();
        bookARoom1 = new JFrames.BookARoom();
        ManageBookingsTab = new javax.swing.JDesktopPane();
        manageBookings2 = new JFrames.ManageBookings();
        ViewReceiptsTab = new javax.swing.JDesktopPane();
        viewReceipts2 = new JFrames.ViewReceipts();
        ManageAddCusTab = new javax.swing.JDesktopPane();
        manageCustomer1 = new JFrames.ManageCustomer();
        ManageStaffTab = new javax.swing.JDesktopPane();
        manageStaff2 = new JFrames.ManageStaff();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TabbedPaneContainer.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabbedPaneContainer.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TabbedPaneContainer.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        TabbedPaneContainer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneContainerStateChanged(evt);
            }
        });

        Workspace.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        Workspace.setMaximumSize(new java.awt.Dimension(757, 478));
        Workspace.setMinimumSize(new java.awt.Dimension(757, 478));
        Workspace.setOpaque(false);

        bookARoom1.setVisible(true);

        Workspace.setLayer(bookARoom1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout WorkspaceLayout = new javax.swing.GroupLayout(Workspace);
        Workspace.setLayout(WorkspaceLayout);
        WorkspaceLayout.setHorizontalGroup(
            WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkspaceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bookARoom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        WorkspaceLayout.setVerticalGroup(
            WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkspaceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bookARoom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TabbedPaneContainer.addTab("<html>Add New<br>Booking<html>", Workspace);

        ManageBookingsTab.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        ManageBookingsTab.setMaximumSize(new java.awt.Dimension(757, 478));
        ManageBookingsTab.setMinimumSize(new java.awt.Dimension(757, 478));

        manageBookings2.setVisible(true);

        ManageBookingsTab.setLayer(manageBookings2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ManageBookingsTabLayout = new javax.swing.GroupLayout(ManageBookingsTab);
        ManageBookingsTab.setLayout(ManageBookingsTabLayout);
        ManageBookingsTabLayout.setHorizontalGroup(
            ManageBookingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageBookingsTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(manageBookings2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ManageBookingsTabLayout.setVerticalGroup(
            ManageBookingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageBookingsTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(manageBookings2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TabbedPaneContainer.addTab("<html><center>Manage<br>Bookings<center><html>", ManageBookingsTab);

        ViewReceiptsTab.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        ViewReceiptsTab.setMaximumSize(new java.awt.Dimension(757, 478));
        ViewReceiptsTab.setMinimumSize(new java.awt.Dimension(757, 478));

        viewReceipts2.setVisible(true);

        ViewReceiptsTab.setLayer(viewReceipts2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ViewReceiptsTabLayout = new javax.swing.GroupLayout(ViewReceiptsTab);
        ViewReceiptsTab.setLayout(ViewReceiptsTabLayout);
        ViewReceiptsTabLayout.setHorizontalGroup(
            ViewReceiptsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewReceipts2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ViewReceiptsTabLayout.setVerticalGroup(
            ViewReceiptsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewReceiptsTabLayout.createSequentialGroup()
                .addComponent(viewReceipts2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TabbedPaneContainer.addTab("View Receipts", ViewReceiptsTab);

        ManageAddCusTab.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        ManageAddCusTab.setMaximumSize(new java.awt.Dimension(757, 478));
        ManageAddCusTab.setMinimumSize(new java.awt.Dimension(757, 478));

        manageCustomer1.setVisible(true);

        ManageAddCusTab.setLayer(manageCustomer1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ManageAddCusTabLayout = new javax.swing.GroupLayout(ManageAddCusTab);
        ManageAddCusTab.setLayout(ManageAddCusTabLayout);
        ManageAddCusTabLayout.setHorizontalGroup(
            ManageAddCusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageCustomer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ManageAddCusTabLayout.setVerticalGroup(
            ManageAddCusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageCustomer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedPaneContainer.addTab("<html><center>Manage/Add<br>Customer<html><center>", ManageAddCusTab);

        ManageStaffTab.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        ManageStaffTab.setMaximumSize(new java.awt.Dimension(757, 478));
        ManageStaffTab.setMinimumSize(new java.awt.Dimension(757, 478));
        ManageStaffTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageStaffTabMouseClicked(evt);
            }
        });

        manageStaff2.setVisible(true);

        ManageStaffTab.setLayer(manageStaff2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ManageStaffTabLayout = new javax.swing.GroupLayout(ManageStaffTab);
        ManageStaffTab.setLayout(ManageStaffTabLayout);
        ManageStaffTabLayout.setHorizontalGroup(
            ManageStaffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageStaffTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(manageStaff2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ManageStaffTabLayout.setVerticalGroup(
            ManageStaffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageStaffTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(manageStaff2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TabbedPaneContainer.addTab("<html><center>Manage<br>Staff<html><center>", ManageStaffTab);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Welcome to Fugi's Hotel Booking System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TabbedPaneContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TabbedPaneContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageStaffTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageStaffTabMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageStaffTabMouseClicked

    private void TabbedPaneContainerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneContainerStateChanged
        // TODO add your handling code here:
        //refresh the desktop panes
        int selectedIndex = TabbedPaneContainer.getSelectedIndex();
        switch (selectedIndex) {
            case 0:
                Workspace.removeAll();
                BookARoom newPane0 = new BookARoom();
                Workspace.add(newPane0);
                newPane0.setVisible(true);
                Workspace.revalidate();
                Workspace.repaint();
            case 1:
                ManageBookingsTab.removeAll();
                ManageBookings newPane1 = new ManageBookings();
                ManageBookingsTab.add(newPane1);
                newPane1.setVisible(true);
                ManageBookingsTab.revalidate();
                ManageBookingsTab.repaint();
            case 2:
                ViewReceiptsTab.removeAll();
                ViewReceipts newPane2 = new ViewReceipts();
                ViewReceiptsTab.add(newPane2);
                newPane2.setVisible(true);
                ViewReceiptsTab.revalidate();
                ViewReceiptsTab.repaint();
            case 3:
                ManageAddCusTab.removeAll();
                ManageCustomer newPane3 = new ManageCustomer();
                ManageAddCusTab.add(newPane3);
                newPane3.setVisible(true);
                ManageAddCusTab.revalidate();
                ManageAddCusTab.repaint();
            case 4:
                //PROTECT THE MANAGE STAFF ACCESS FOR OWNER ONLY USING owner's password
                //set password and target pane
                int manageStaff = 4;
                String accessPw = "owner666";

                //check if targetPane is selected
                if (!pauseTabChange && selectedIndex == 4) {
                    //pause the above if condition to prevent loops and show the other tab first
                    pauseTabChange = true;
                    TabbedPaneContainer.setSelectedIndex(0);

                    String pwInput = JOptionPane.showInputDialog(null, "Enter the password:");
                    if (pwInput != null && pwInput.equals(accessPw)) {
                        // Password is correct, show the protected tab
                        TabbedPaneContainer.setSelectedIndex(manageStaff);
                        //refresh the pane to include changes
                        ManageStaffTab.removeAll();
                        ManageStaff newPane4 = new ManageStaff();
                        ManageStaffTab.add(newPane4);
                        newPane4.setVisible(true);
                        ManageStaffTab.revalidate();
                        ManageStaffTab.repaint();
                    } else {
                        // Password is incorrect or cancelled, do not show the protected tab
                        JOptionPane.showMessageDialog(null, "Incorrect password, access denied! Only owners can access staff records.");
                    }
                    //resume if condition
                    pauseTabChange = false;
                }

        }
//        


    }//GEN-LAST:event_TabbedPaneContainerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    public void clearWorkspace() {
        Workspace.removeAll();
    }

    public JDesktopPane getWorkspace() {
        return Workspace;
    }

    public JDesktopPane getjDesktopPane1() {
        return Workspace;
    }

    public void addToWorkspace(JInternalFrame frame) {
        Workspace.add(frame);
    }

    public void closeAndShowNextFrame(JInternalFrame nextFrame) {
        Workspace.removeAll();
        Workspace.add(nextFrame).setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane ManageAddCusTab;
    private javax.swing.JDesktopPane ManageBookingsTab;
    private javax.swing.JDesktopPane ManageStaffTab;
    private javax.swing.JTabbedPane TabbedPaneContainer;
    private javax.swing.JDesktopPane ViewReceiptsTab;
    private javax.swing.JDesktopPane Workspace;
    private JFrames.BookARoom bookARoom1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private JFrames.ManageBookings manageBookings2;
    private JFrames.ManageCustomer manageCustomer1;
    private JFrames.ManageStaff manageStaff2;
    private JFrames.ViewReceipts viewReceipts2;
    // End of variables declaration//GEN-END:variables
}
